import { chromium } from '@playwright/test';
const [sid, tok, out, w] = process.argv.slice(2);
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream'] });
const ctx = await b.newContext({ permissions: ['microphone'], viewport: { width: Number(w||1280), height: 900 } });
const p = await ctx.newPage();
p.on('console', m => m.type()==='error' && console.log('console', m.type(), m.text().slice(0,300)));
await p.goto(`http://localhost:3103/live/${sid}#t=${tok}`);
await p.getByRole('button', { name: 'Continue' }).waitFor();
await p.screenshot({ path: `${out}-1-intro.png`, fullPage: true });
await p.getByRole('button', { name: 'Continue' }).click();
await p.getByLabel(/I understand/).check();
await p.screenshot({ path: `${out}-2-consent.png`, fullPage: true });
await p.getByRole('button', { name: 'Agree and continue' }).click();
await p.getByRole('button', { name: /Allow microphone/ }).click();
await p.getByRole('button', { name: 'Join the call' }).waitFor();
await p.waitForTimeout(800);
await p.screenshot({ path: `${out}-3-devices.png`, fullPage: true });
await p.getByRole('button', { name: 'Join the call' }).click();
await p.getByTestId('call-status').filter({ hasText: 'Live' }).waitFor();
await p.waitForTimeout(2500);
await p.getByTestId('typed-input').fill('Hello there, I am ready to start the interview.');
await p.getByRole('button', { name: 'Send' }).click();
await p.waitForTimeout(3000);
await p.screenshot({ path: `${out}-4-call.png`, fullPage: true });
await p.getByTestId('end-call').click();
await p.waitForTimeout(500);
await p.screenshot({ path: `${out}-5-confirm.png` });
await p.getByTestId('confirm-end').click();
await p.getByTestId('end-screen').waitFor();
await p.screenshot({ path: `${out}-6-end.png`, fullPage: true });
await b.close();
