'use client';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import useSWR from 'swr';
import { Alert, Badge, Card, Loading, SimulatedBadge, Spinner } from '@/components/ui';
import { OverallScore, ScoreBar, mmss } from '@/components/review/score';
import type { ParticipantReport } from '@/components/review/types';
import { ApiError, api } from '@/lib/api';
import { formatDate, formatDuration } from '@/lib/format';
import { readSessionToken } from '@/lib/live/token';

/**
 * Participant-facing report. Auth: the session token (`cfs_…`) kept in session/local storage by the
 * live call page (or a `#t=` fragment), falling back to the logged-in user's own session. The API only
 * returns the sections the scenario version allows.
 */
async function loadReport(sessionId: string, token: string | null): Promise<ParticipantReport> {
  if (token) {
    try {
      return await api<ParticipantReport>(`/runtime/sessions/${encodeURIComponent(sessionId)}/report`, { token });
    } catch (e) {
      if (!(e instanceof ApiError) || (e.status !== 401 && e.status !== 404)) throw e;
    }
  }
  return api<ParticipantReport>(`/me/sessions/${encodeURIComponent(sessionId)}/report`);
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return <Card title={title}>{children}</Card>;
}

export default function ParticipantReportPage() {
  const { sessionId } = useParams<{ sessionId: string }>();
  const [token, setToken] = useState<string | null | undefined>(undefined);
  const [showTranscript, setShowTranscript] = useState(false);

  useEffect(() => setToken(readSessionToken(sessionId)), [sessionId]);

  const { data, error } = useSWR<ParticipantReport>(token === undefined ? null : ['participant-report', sessionId, token ?? ''], () => loadReport(sessionId, token ?? null), {
    refreshInterval: (d) => (d?.processing.pending ? 4000 : 0),
    shouldRetryOnError: false,
  });

  if (error) {
    const expired = error instanceof ApiError && (error.status === 401 || error.status === 404);
    return (
      <main className="mx-auto max-w-lg px-4 py-16 text-center">
        <h1 className="text-lg font-semibold text-slate-900">{expired ? 'Report not available' : 'Something went wrong'}</h1>
        <p className="mt-2 text-sm text-slate-600">
          {expired
            ? 'This feedback link has expired or was opened on a different device. If you have an account, sign in to see your sessions.'
            : error instanceof Error
              ? error.message
              : 'Please try again.'}
        </p>
        {expired && (
          <Link href={`/login?next=${encodeURIComponent(`/report/${sessionId}`)}`} className="mt-4 inline-block text-brand-700 hover:underline">
            Sign in
          </Link>
        )}
      </main>
    );
  }
  if (!data) return <Loading label="Loading your report…" />;

  const r = data;
  const nothingVisible = !r.visibility.transcript && !r.visibility.feedback && !r.visibility.scores;
  return (
    <main className="mx-auto max-w-3xl px-4 py-8">
      <header className="mb-6">
        {r.branding?.logoUrl && <img src={r.branding.logoUrl} alt="" className="mb-3 h-8 w-auto" />}
        <p className="text-xs font-medium uppercase tracking-wide text-slate-500">{r.workspace.name}</p>
        <h1 className="mt-1 flex flex-wrap items-center gap-2 text-2xl font-semibold text-slate-900">
          Your feedback: {r.scenario.name}
          {r.simulated && <SimulatedBadge />}
        </h1>
        <p className="mt-1 text-sm text-slate-600">
          {formatDate(r.session.endedAt ?? r.session.createdAt)} · {formatDuration(r.session.durationMs)}
        </p>
      </header>

      <div className="space-y-4">
        {r.processing.pending && (
          <div className="flex items-center gap-3 rounded-md border border-sky-200 bg-sky-50 p-4 text-sm text-sky-900" role="status" aria-live="polite">
            <Spinner className="h-4 w-4" /> Your feedback is being prepared… This page updates automatically.
          </div>
        )}
        {!r.processing.pending && r.processing.message && <Alert tone="info">{r.processing.message}</Alert>}
        {r.simulated && (
          <Alert tone="warning" title="Practice feedback (simulated)">
            This feedback was generated by a local simulator because no AI provider is configured. It is a rough, automated heuristic — not a real
            assessment.
          </Alert>
        )}
        {nothingVisible && <Alert tone="info">Thanks for taking part. The organizer has chosen not to share feedback for this session.</Alert>}

        {r.scores &&
          (r.scores.awaitingReview ? (
            <Alert tone="info" title="Scores are being reviewed">
              A reviewer checks the results before scores are shared. Please check back later.
            </Alert>
          ) : (
            <Section title="Your scores">
              <OverallScore score={r.scores.overallScore} />
              <ul className="mt-4 space-y-3">
                {r.scores.criteria.map((c) => (
                  <li key={c.name}>
                    <div className="mb-1 flex justify-between text-sm">
                      <span className="font-medium text-slate-800">{c.name}</span>
                      <span className="text-xs text-slate-500">weight {c.weight}%</span>
                    </div>
                    <ScoreBar score={c.score} label={c.name} />
                  </li>
                ))}
              </ul>
            </Section>
          ))}

        {r.feedback && (
          <>
            {r.feedback.summary && (
              <Section title="Summary">
                <p className="whitespace-pre-line text-sm text-slate-800">{r.feedback.summary}</p>
              </Section>
            )}
            <div className="grid gap-4 md:grid-cols-2">
              <Section title="What went well">
                <FeedbackList items={r.feedback.strengths} />
              </Section>
              <Section title="What to work on">
                <FeedbackList items={r.feedback.weaknesses} />
              </Section>
            </div>
            <Section title="Next steps">
              <FeedbackList items={r.feedback.improvements} />
            </Section>
          </>
        )}
        {r.visibility.feedback && !r.feedback && !r.processing.pending && r.processing.status !== 'SKIPPED' && (
          <p className="text-sm text-slate-500">No written feedback is available for this session.</p>
        )}

        {r.transcript && (
          <Card
            title={`Transcript (${r.transcript.length} turns)`}
            actions={
              <button className="text-sm text-brand-700 hover:underline" aria-expanded={showTranscript} onClick={() => setShowTranscript((v) => !v)}>
                {showTranscript ? 'Hide' : 'Show'}
              </button>
            }
          >
            {showTranscript ? (
              <ol className="space-y-2">
                {r.transcript.map((t) => (
                  <li key={t.seq} className={t.speaker === 'PARTICIPANT' ? 'rounded-md bg-sky-50 p-2' : 'rounded-md bg-slate-50 p-2'}>
                    <p className="text-xs text-slate-500">
                      <span className="font-semibold">{t.speaker === 'PARTICIPANT' ? 'You' : 'Agent'}</span> {mmss(t.startedAtMs)}
                    </p>
                    <p className="whitespace-pre-wrap text-sm text-slate-900">{t.text}</p>
                  </li>
                ))}
              </ol>
            ) : (
              <p className="text-sm text-slate-500">The full conversation is available here.</p>
            )}
          </Card>
        )}
      </div>
      {!r.branding?.hidePoweredBy && (
        <p className="mt-8 text-center text-xs text-slate-400">
          Powered by ConversaForge <Badge className="ml-1">session {r.session.id.slice(-6)}</Badge>
        </p>
      )}
    </main>
  );
}

function FeedbackList({ items }: { items: string[] }) {
  if (!items?.length) return <p className="text-sm text-slate-500">—</p>;
  return (
    <ul className="list-disc space-y-1 pl-5 text-sm text-slate-800">
      {items.map((s, i) => (
        <li key={i}>{s}</li>
      ))}
    </ul>
  );
}
