#!/usr/bin/env bash
# (Re)generate the initial production migration from the current Prisma schema plus the raw SQL
# objects Prisma cannot express (prisma/sql/post-push.sql). Only for pre-launch; after launch, add
# new migrations with `pnpm prisma:dev --name <change>` instead of regenerating this one.
set -euo pipefail
cd "$(dirname "$0")/.."
DIR=prisma/migrations/20260925000000_init
rm -rf prisma/migrations
mkdir -p "$DIR"
npx prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --script > "$DIR/migration.sql"
{
  echo ""
  echo "-- ─── Raw SQL objects (from prisma/sql/post-push.sql) ───"
  cat prisma/sql/post-push.sql
} >> "$DIR/migration.sql"
printf '# Please do not edit this file manually\n# It should be added in your version-control system (e.g., Git)\nprovider = "postgresql"\n' > prisma/migrations/migration_lock.toml
echo "Wrote $DIR/migration.sql ($(wc -l < "$DIR/migration.sql") lines)"
